
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: PBFA97CFB590B2093
  url: http://prometheus:9090
  user: admin
  secureJsonData:
    password: admin
- name: mysql
  type: mysql
  url: mysqldb:3306
  uid: P430005175C4C7810
  jsonData:
      database: Users
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
  user: root
  secureJsonData:
    password: root
