
apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  user: admin
  secureJsonData:
    password: admin
- name: mysql
  type: mysql
  url: mysqldb:3306
  user: root
  secureJsonData:
    password: root
