FROM node:16.17.1-alpine
ENV NODE_ENV=production
COPY ["Frontend/eia-client/package.json", "Frontend/eia-client/package-lock.json*", "Frontend/eia-client/npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
RUN chown -R node /Frontend/eia-client
WORKDIR Frontend/eia-client
USER node
CMD ["npm", "start"]
