# FROM eclipse-temurin:17-jdk-alpine
# VOLUME /tmp
# COPY /src/main/resources/application.properties application.properties
# COPY  EIA_project.jar app.jar
# EXPOSE 8080
# CMD ["java","-jar","app.jar","--spring.config.name=application", "--spring.config.location=/application.properties"]
FROM nginx
RUN apt-get update -y
RUN apt-get install openjdk-17-jre-headless -y
RUN apt-get install openjdk-17-jdk -y
RUN curl -LO https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz 
RUN tar -xvf apache-maven-3.9.6-bin.tar.gz 
ENV PATH "$PATH:/apache-maven-3.9.6/bin"
COPY  Backend/app backend
WORKDIR backend
CMD ["/bin/sh","-c","ls; mvn spring-boot:run"]